src/apps/accounts/urls.py
from django.urls import path

from apps.accounts import views as app_views

urlpatterns = [
    path('profile', app_views.ProfileView.as_view(), name='detail'),
    path('profile/update', app_views.ProfileUpdateView.as_view(), name='update'),
    path('profile/email', app_views.ProfileUpdateView.as_view(), name='email'),
    path('profile/deposit', app_views.ProfileDepositView.as_view(), name='deposit'),
]

src/apps/core/urls.py
from django.urls import path

from apps.core import views as app_views

urlpatterns = [
    path('', app_views.IndexView.as_view(), name='index'),
    path('recently', app_views.AfterLoginView.as_view(), name='recently'),
    path('history', app_views.HistoryListView.as_view(), name='history'),
    path('open-bets', app_views.OpenBetsListView.as_view(), name='open-bets'),
    path('event/<int:pk>', app_views.EventDetailView.as_view(), name='event-details'),
    path('event/<int:pk>/bet', app_views.EventBetView.as_view(), name='place-bet'),
]

src/apps/users/urls.py
from django.urls import path, re_path

from apps.users import views as app_views

urlpatterns = [
    path('signup/', app_views.SignUpView.as_view(), name='signup'),
    path('ref/<int:pk>/signup', app_views.ReferralView.as_view(), name='ref'),
    path('activate/<str:uid_str>/<str:token>/', app_views.ConfirmEmailView.as_view(), name='email-confirm'),
    path('logout', app_views.SignOutView.as_view(), name='logout'),
]

src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include(('apps.accounts.urls', 'apps.accounts'), namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('charges/', include(('apps.charges.urls', 'apps.charges'), namespace='charges')),
    path('', include(('apps.core.urls', 'apps.core'), namespace='core')),
    path('', include(('apps.users.urls', 'apps.users'), namespace='users')),
    path('admin/', admin.site.urls),
    path('jet', include('jet.urls', namespace='jet')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/apps/core/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import ugettext_lazy as _
from model_utils import Choices
from solo.models import SingletonModel

import settings
from apps.common.models import TimeStampedModel


class Athlete(TimeStampedModel):
    name = models.CharField(max_length=191)
    slug = models.CharField(unique=True, max_length=191)
    details = models.TextField(blank=True, null=True)
    image = models.CharField(max_length=191, blank=True, null=True)

    class Meta:
        verbose_name = _('athlete')
        verbose_name_plural = _('athletes')


class Bet(TimeStampedModel):
    STATUS_CHOICES = Choices(
        (None, 'WAIT', _('Wait')),
        (True, 'WON', _('Won')),
        (False, 'LOS', _('Lost')),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, models.PROTECT,
                             related_name='bets')
    event = models.ForeignKey('Event', models.PROTECT, related_name='+')
    team = models.ForeignKey('Team', on_delete=models.CASCADE, null=True)

    amount = models.DecimalField(max_digits=20, decimal_places=2,
                                 editable=False)
    system_fee = models.DecimalField(max_digits=20, decimal_places=2,
                                     default=0, editable=False)
    status = models.NullBooleanField(verbose_name=_('status'), default=None,
                                     choices=STATUS_CHOICES)

    class Meta:
        unique_together = (
            ('user', 'event')
        )
        verbose_name = _('bet')
        verbose_name_plural = _('bets')

    def get_event_id(self):
        first_letter = self.event.category.name[0].upper()
        event_id = self.event_id
        return '{letter}{event_id}'.format(letter=first_letter,
                                           event_id=event_id)


class EventCategory(TimeStampedModel):
    name = models.CharField(_('name'), max_length=256)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = _('event category')
        verbose_name_plural = _('event categories')


class Event(TimeStampedModel):
    published = models.BooleanField(_('published'), default=False)
    name = models.CharField(_('title'), max_length=191)
    slug = models.SlugField(_('slug'), unique=True)
    notes = models.TextField(_('details'), blank=True, null=True)
    starts_at = models.DateTimeField(_('starts at'), blank=True, null=True)
    category = models.ForeignKey(EventCategory, models.PROTECT,
                                 related_name='+',
                                 verbose_name=_('category'))
    logo = models.FileField(_('logo'), default='', blank=True)
    logo_url = models.CharField(_('logo url'), default='', blank=True,
                                max_length=1024)
    teams = models.ManyToManyField('Team', blank=True,
                                   verbose_name=_('teams'))

    def __str__(self):
        return 'Event: {} - {}'.format(self.name, self.starts_at)

    class Meta:
        verbose_name = _('event')
        verbose_name_plural = _('events')

    def clean(self):
        if self.published and not self.logo and not self.logo_url:
            raise ValidationError({
                'logo': _('Logo or Logo Url field is required on '
                          'publishing step'),
                'logo_url': _('Logo or Logo Url field is required on '
                              'publishing step'),
            })


class Team(TimeStampedModel):
    name = models.CharField(_('name'), max_length=256)
    slug = models.SlugField(_('slug'), unique=True)
    details = models.TextField(_('details'), blank=True, null=True)
    athletes = models.ManyToManyField('Athlete', related_name='teams',
                                      verbose_name=_('athletes'), blank=True)
    image = models.CharField(max_length=191, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('team')
        verbose_name_plural = _('teams')


class Transaction(TimeStampedModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, models.PROTECT,
                             related_name='+')
    base_type = models.IntegerField()
    amount = models.IntegerField()
    bet = models.ForeignKey(Bet, models.PROTECT, related_name='+', blank=True,
                            null=True)
    details = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = _('transaction')
        verbose_name_plural = _('transactions')


class SiteConfig(SingletonModel):

    bet_percent = models.DecimalField(verbose_name=_('bet percent'), max_digits=10,
                                      decimal_places=2, default=0)

    class Meta:
        verbose_name = _('site config')
        verbose_name_plural = _('site config')

src/apps/core/views.py
from decimal import Decimal

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.views import generic
from django_filters.views import FilterView

from apps.common.views import UserProfileRequiredMixin
from apps.core import models
from apps.core.filters import EventFilter
from apps.core.models import SiteConfig


class IndexView(generic.TemplateView):
    template_name = 'core/index.html'


class AfterLoginView(UserProfileRequiredMixin, LoginRequiredMixin,
                     FilterView):
    template_name = 'core/after-login.html'
    queryset = models.Event.objects.filter(published=True)
    paginate_by = 10
    filterset_class = EventFilter

    def get_queryset(self):
        return self.queryset.filter(starts_at__date=timezone.now().date())

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context[''] = models.EventCategory.objects.all()
        context['categories'] = models.EventCategory.objects.all()
        context['upcoming_events'] = models.Event.objects.all().order_by(
            '-starts_at')[:20]
        return context


class BaseBetsListView(generic.ListView):
    template_name = 'core/bets.html'
    paginate_by = 20
    page_title = ''

    def get_queryset(self):
        return self.request.user.bets.all().order_by('-created_at')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['page_title'] = self.page_title
        context['upcoming_events'] = models.Event.objects.filter(
            starts_at__gte=timezone.now() + timezone.timedelta(hours=1)
        ).order_by('-starts_at')[:20]
        return context


class HistoryListView(UserProfileRequiredMixin, LoginRequiredMixin,
                      BaseBetsListView):
    page_title = _('History')


class OpenBetsListView(UserProfileRequiredMixin, LoginRequiredMixin,
                       BaseBetsListView):
    page_title = _('Open Bets')

    def get_queryset(self):
        return super().get_queryset().filter(
            status=models.Bet.STATUS_CHOICES.WAIT
        )


class EventDetailView(generic.DetailView):
    template_name = 'core/event-detail.html'
    model = models.Event

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['upcoming_events'] = models.Event.objects.filter(
            starts_at__gte=timezone.now() + timezone.timedelta(hours=1)
        ).order_by('-starts_at')[:20]
        return context


class EventBetView(generic.CreateView):
    template_name = 'core/event-bet.html'
    model = models.Bet
    fields = ('team', 'amount')

    def get_success_url(self):
        return reverse('core:place-bet', args=[self.event.id])

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields['team'].queryset = self.event.teams.all()
        return form

    def dispatch(self, request, *args, **kwargs):
        self.event = get_object_or_404(models.Event, pk=kwargs['pk'])
        self.already_exists = self.request.user.bets.filter(
            event_id=self.event.id).exists()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['event'] = self.event
        context['upcoming_events'] = models.Event.objects.filter(
            starts_at__gte=timezone.now() + timezone.timedelta(hours=1)
        ).order_by('-starts_at')[:20]
        if self.already_exists:
            context['registered_bet'] = self.request.user.bets.get(
                event_id=self.event.id)
        return context

    @transaction.atomic
    def form_valid(self, form):
        if self.already_exists:
            messages.info(self.request, _('Bet for this event already exists'))
            return HttpResponseRedirect(self.get_success_url())
        current_account = self.request.user.account
        account = type(current_account).objects.select_for_update().get(
            pk=current_account.pk
        )
        if account.deposit < form.cleaned_data['amount']:
            messages.info(self.request,
                          _('You have to replenish your deposit'))
            return HttpResponseRedirect(self.get_success_url())
        self.object = form.save(commit=False)
        site_config = SiteConfig.get_solo()
        self.object.system_fee = self.object.amount * \
                                 site_config.bet_percent / Decimal(100.0)
        account.deposit = F('deposit') - self.object.amount
        self.object.amount -= self.object.system_fee
        self.object.event_id = self.event.id
        self.object.user_id = self.request.user.id
        self.object.save()
        account.save(update_fields=['deposit'])
        return HttpResponseRedirect(self.get_success_url())

src/templates/core/after-login.html
{% extends 'core/dashboard-base.html' %}
{% load static i18n widget_tweaks %}

{% block extra-content %}
  <section class="main-content-section section-padding">
    <div class="container">
      <div class="row">

        <!-- main contents wrapper -->
        <div class="col-md-8 clearfix">
          <div class="main-content-wrapper bet-wrapper">
            <!-- title -->
            <div class="inner-section-title">
              <div class="col-md-4">
                <h2><i class="fas fa-history"></i> Todays Event</h2>
              </div>
              <!-- filter options -->
              <div class="filter-option col-md-8">
                <form>
                  <div class="form-row align-items-center">

                    <div class="col-sm-6">
                      <label class="sr-only"
                             for="inlineFormInputGroup">search</label>
                      <div class="input-group">
                        {% render_field filter.form.query class="form-control" id="inlineFormInputGroup" placeholder="search" autofocus="" %}
                        <div class="input-group-prepend">
                          <div class="input-group-text"><a href="javascript:$('form').submit()"><i
                                  class="fas fa-search"></i></a></div>
                        </div>
                      </div>
                    </div>

                    <div class="col-sm-6">
                      <label class="sr-only"
                             for="inlineFormInputGroup">select</label>
                      <div class="input-group">
                        {% render_field filter.form.category class="form-control" placeholder="1231" %}
                      </div>
                    </div>

                  </div>
                </form>
              </div>
            </div>

            <!-- event widgets wrapper -->
            <div class="event-widget-wrapper clearfix">
              <!-- single bet widget ends -->

              {% for event in object_list %}
                <div class="single-bet-widget">
                  <div class="media">
                    <div class="media-left">
                      <a href="{% url 'core:event-details' pk=event.pk %}">
                        <img src="{% static "assets/images/bet/bet1.png" %}"
                             alt="">
                      </a>
                    </div>
                    <div class="media-body">
                      <!-- bet details -->
                      <div class="bet-details">
                        <h2>{{ event.name }}</h2>
                        <div class="date">
                          <a href="javascript:void(0);">
                            <i class="fas fa-calendar-alt"></i>
                            {{ event.starts_at|date:'d/m/Y' }}
                          </a>
                          <a href="javascript:void(0);">
                            <i class="fas fa-clock"></i>
                            {{ event.starts_at|date:'f A' }}
                          </a>
                        </div>
                        <a href="{% url 'core:event-details' pk=event.pk %}" class="team-name">
                          {{ event.teams.all|join:', ' }}
                        </a>
                        <p>{{ event.notes|default:"Lorem Ipsum is simply dummy text of the printing typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since" }}.</p>
                      </div>

                      <!-- bet buttons -->
                      <div class="bet-buttons">
                        <a href="#" class="btn-common btn-primary"><i
                                class="fas fa-dollar-sign"></i> Place bet</a>
                        <!--a href="#" class="btn-common btn-tertiary"><i
                                class="far fa-play-circle"></i> Watch live</a-->
                      </div>
                    </div>
                  </div>
                </div>
              {% empty %}
                <div class="single-bet-widget">
                  <div class="media">
                    <div class="media-body">{% trans 'Empty' %}</div>
                  </div>
                </div>
              {% endfor %}
            </div>
            <!-- event widgets wrapper ends -->
            <!-- pagination -->
            <div class="pagination-wrapper text-right">

              {% if page_obj.has_previous %}
                <a href="{% url 'core:recently' %}?page={{ page_obj.previous_page_number }}"
                   class="pagination pagi-next"><i
                        class="fas fa-angle-left"></i></a>
              {% endif %}

              {% if page_obj.has_next %}
                <a href="{% url 'core:recently' %}?page={{ page_obj.next_page_number }}"
                   class="pagination pagi-prev"><i
                        class="fas fa-angle-right"></i></a>
              {% endif %}
            </div>
          </div>
        </div>
        <!-- main contents wrapper ends -->

        <!-- sidebar wrapper -->
        <div class="col-md-4 clearfix">
          <aside class="sidebar-wrapper clearfix">
            <!-- Single Sidebar -->
            <div class="single-sidebar">
              <!-- title -->
              <div class="inner-section-title">
                <h2><i class="fas fa-calendar-alt"></i> Upcoming Events</h2>
              </div>

              <!-- sidebar widget -->
              <div class="sidebar-widget clearfix">
                <!-- single widget card -->
                {% for event in upcoming_events %}
                  {% include 'includes/single-event.html' with event=event %}
                {% endfor %}
                <!-- single widget card ends -->
              </div>
            </div>

            <!-- Single Sidebar Ends -->
          </aside>
        </div>
        <!-- sidebar wrapper ends -->

      </div>
    </div>
  </section>
{% endblock %}

src/templates/core/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block head-title %}{% endblock %}</title>
  <meta charset="UTF-8">
  <link rel="stylesheet"
        href="{% static 'packages/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  <link rel="stylesheet"
        href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
        integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
        crossorigin="anonymous">
  {% block head-js %}{% endblock %}
  {% block head-css %}{% endblock %}
</head>
<body>
<div class="container-fluid full-size main-bg">
  <div class="d-flex align-items-center justify-content-between pt-3 pb-3 first-header">
    <h2 class="text-uppercase"><strong>Imbting</strong></h2>
    <div class="btns-header">
      <a class="btn btn-danger text-uppercase im-btn-danger"
         href="{% url 'login' %}">
        Login
      </a>
      <a class="btn btn-success text-uppercase im-btn-success"
         href="{% url 'users:signup' %}">
        Sign up
      </a>
    </div>
  </div>

  <div class="row justify-content-between pb-2 pt-2 second-header">
    <div class="col-3 d-flex align-items-center">
      <a href="{% url 'core:index' %}">
        <i class="fas fa-home"></i>
        <span class="ml-2 text-uppercase">Home</span>
      </a>
    </div>
    <div class="col-2 text-right d-flex align-items-center justify-content-between">
      <span class="mr-1">1:34 PM</span>
      <div class="d-inline-block mr-1 icon-header">
        <i class="far fa-question-circle"></i>
      </div>
      <div class="d-inline-block icon-header">
        <i class="far fa-envelope"></i>
      </div>
      <div class="d-inline-block icon-header">
        <i class="far fa-comment-dots"></i>
      </div>
      <div class="d-inline-block btn-language">
        <form action="{% url 'set_language' %}" method="post" id="lang-form">
          {% csrf_token %}
          <input name="next" type="hidden" value="{{ redirect_to }}"/>
          <select name="language" class="form-control"
                  onchange="document.getElementById('lang-form').submit()">
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
              <option value="{{ language.code }}"
                      {% if language.code == LANGUAGE_CODE %}
                      selected{% endif %}>
                {{ language.name_local }} ({{ language.code }})
              </option>
            {% endfor %}
          </select>
        </form>
      </div>
    </div>
  </div>

  <div class="row">{% block content %}{% endblock %}</div>

  <div class="row footer">
    <div class="col-12 text-center pt-3 pb-3">
      <ul class="list-inline">
        <li class="list-inline-item mr-3"><strong>Forms&Agreements</strong>
        </li>
        <li class="list-inline-item mr-3"><strong>Responsible Gambling</strong>
        </li>
        <li class="list-inline-item mr-3"><strong>Terms of Service</strong>
        </li>
        <li class="list-inline-item mr-3"><strong>Privacy Policy</strong></li>
        <li class="list-inline-item"><strong>Disclaimer</strong></li>
      </ul>
      <small>
        Gambling should be entertaining. Remember that you always risk losing
        the money you bet, so do not spend more than you can afford to lose. If
        you think you may have a problem,
        <a href="#" class="footer-link">click here</a>.
      </small>
    </div>
  </div>
</div>

<script src="{% static 'packages/jquery/jquery-3.3.1.slim.min.js' %}"></script>
<script src="{% static 'packages/bootstrap/js/bootstrap.min.js' %}"></script>

</body>
</html>

{#<div class="text-right" style="float: right; margin: 30px;">#}
{#  <form action="{% url 'set_language' %}" method="post" id="lang-form">#}
{#    {% csrf_token %}#}
{#    <input name="next" type="hidden" value="{{ redirect_to }}"/>#}
{#    <div class="col-sm-12">#}
{#      <select name="language" class="form-control" onchange="document.getElementById('lang-form').submit()">#}
{#        {% get_current_language as LANGUAGE_CODE %}#}
{#        {% get_available_languages as LANGUAGES %}#}
{#        {% get_language_info_list for LANGUAGES as languages %}#}
{#        {% for language in languages %}#}
{#          <option value="{{ language.code }}"#}
{#                  {% if language.code == LANGUAGE_CODE %} selected{% endif %}>#}
{#            {{ language.name_local }} ({{ language.code }})#}
{#          </option>#}
{#        {% endfor %}#}
{#      </select>#}
{#    </div>#}
{#  </form>#}
{#</div>#}

src/templates/core/bets.html
{% extends 'core/dashboard-base.html' %}
{% load static i18n list_converter %}

{% block extra-content %}
  <section class="main-content-section section-padding">
    <div class="container">
      <div class="row">

        <!-- main contents wrapper -->
        <div class="col-md-8 clearfix">
          <div class="main-content-wrapper">
            <!-- title -->
            <div class="inner-section-title">
              <h2><i class="far fa-folder-open"></i> {{ page_title }}</h2>
            </div>

            <!-- event widgets wrapper -->
            <div class="event-widget-wrapper clearfix">

              <!-- event widgets -->
              <div class="event-widgets">
                <!-- single event widget -->
                {% for bet_group in object_list|convert_list_by_range:'created_at' %}
                  <div class="event-date">
                    <h3>{{ bet_group.date|date:'d / m / Y' }}</h3>
                  </div>
                  {% for bet in bet_group.items %}
                    <div class="single-event-widget">
                      <!-- event details -->
                      <div class="event-details">
                        <p>Event ID: <span>{{ bet.get_event_id }}</span></p>
                        <p>Event Name:
                          <span>{{ bet.event.category.name }} Event</span></p>
                        <p>Bet Placed: <span>${{ bet.amount }}</span></p>
                        <p>Bet Place on: <span>{{ bet.team.name }}</span></p>
                      </div>
                      <!-- event status -->
                      <div class="event-status">
                        <p>Status: <span>{{ bet.get_status_display }}</span>
                        </p>
                      </div>
                    </div>
                  {% endfor %}
                {% empty %}
                  <span>{% trans 'Empty' %}</span>
                {% endfor %}
                <!-- single event widget ends -->
              </div>
            </div>

            <!-- pagination -->
            <div class="pagination-wrapper text-right">
              {% if page_obj.has_previous %}
                <a href="{% url 'core:recently' %}?page={{ page_obj.previous_page_number }}"
                   class="pagination pagi-next"><i
                        class="fas fa-angle-left"></i></a>
              {% endif %}

              {% if page_obj.has_next %}
                <a href="{% url 'core:recently' %}?page={{ page_obj.next_page_number }}"
                   class="pagination pagi-prev"><i
                        class="fas fa-angle-right"></i></a>
              {% endif %}
            </div>

          </div>
        </div>
        <!-- main contents wrapper ends -->

        <!-- sidebar wrapper -->
        <div class="col-md-4 clearfix">
          <aside class="sidebar-wrapper clearfix">
            <!-- Single Sidebar -->
            <div class="single-sidebar">
              <!-- title -->
              <div class="inner-section-title">
                <h2><i class="fas fa-calendar-alt"></i> Upcoming Events</h2>
              </div>

              <!-- sidebar widget -->
              <div class="sidebar-widget clearfix">
                <!-- single widget card -->
                {% for event in upcoming_events %}
                  {% include 'includes/single-event.html' with event=event %}
                {% endfor %}
              </div>
            </div>
            <!-- Single Sidebar Ends -->
          </aside>
        </div>
        <!-- sidebar wrapper ends -->

      </div>
    </div>
  </section>

{% endblock %}

src/templates/core/dashboard-base.html
{% extends 'core/base.html' %}
{% load static i18n %}

{% block content %}
  <header class="header-section">
    <!-- top header -->
    <div class="top-header">
      <div class="container">
        <div class="row justify-content-between align-items-center">

          <!-- logo -->
          <div class="logo">
            <a href="{% url 'core:recently' %}">
              <img src="{% static "assets/images/logo.png" %}"
                   alt="Imbeting logo">
            </a>
          </div>
          <!-- logo ends -->

          <!-- user info -->
          <div class="header-user-info">
            <ul>
              <li><a href="{% url 'core:open-bets' %}"><i
                      class="fas fa-shield-alt"></i> {% trans 'Open bets' %}</a>
              </li>
              <li><a href="{% url 'core:history' %}"><i
                      class="far fa-clock"></i> {% trans 'History' %}</a></li>
              <li><a href="{% url 'accounts:deposit' %}"><i class="fas fa-briefcase"></i> {% trans 'Deposit' %}</a></li>
              <li class="user-id"><a href="{% url 'accounts:detail' %}"><i
                      class="far fa-user-circle"></i> {% now "d / m / Y" %}</a>
              </li>
            </ul>
          </div>
          <!-- user info ends -->

        </div>
      </div>
    </div>
    <!-- top header ends -->

  </header>

  <section class="status-bar-section">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <!-- bar -->
          <div class="status-bar">
            <ul>
              <li>
                <a href="#">{% trans 'Current Balance' %}: <span>{{ user.account.get_deposit_value|default:0 }}&nbsp;MXN</span></a>
                <a href="#">{% trans 'Amount at Risk' %}: <span>{{ user.account.get_risk_value|default:0 }}&nbsp;MXN</span></a>
                <a href="#">{% trans 'Available Balance' %}: <span>{{ user.account.get_available_value|default:0 }}&nbsp;MXN</span></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>
  {% block extra-content %}{% endblock %}
{% endblock %}