src/apps/accounts/urls.py
from django.urls import path

from apps.accounts import views as app_views

urlpatterns = [
    path('profile', app_views.ProfileView.as_view(), name='detail'),
    path('profile/update', app_views.ProfileUpdateView.as_view(), name='update'),
    path('profile/email', app_views.ProfileUpdateView.as_view(), name='email'),
    path('profile/deposit', app_views.ProfileDepositView.as_view(), name='deposit'),
]

src/apps/charges/urls.py
from django.urls import path

from apps.charges import views as app_views

urlpatterns = [
    path('charge', app_views.ChargeCreateView.as_view(), name='charge'),
    path('charge/status', app_views.ChargeStatusView.as_view(), name='charge-status'),
]

src/apps/core/urls.py
from django.urls import path

from apps.core import views as app_views

urlpatterns = [
    path('', app_views.IndexView.as_view(), name='index'),
    path('recently', app_views.AfterLoginView.as_view(), name='recently'),
    path('history', app_views.HistoryListView.as_view(), name='history'),
    path('open-bets', app_views.OpenBetsListView.as_view(), name='open-bets'),
    path('event/<int:pk>', app_views.EventDetailView.as_view(), name='event-details'),
    path('event/<int:pk>/bet', app_views.EventBetView.as_view(), name='place-bet'),
]

src/apps/users/urls.py
from django.urls import path, re_path

from apps.users import views as app_views

urlpatterns = [
    path('signup/', app_views.SignUpView.as_view(), name='signup'),
    path('ref/<int:pk>/signup', app_views.ReferralView.as_view(), name='ref'),
    path('activate/<str:uid_str>/<str:token>/', app_views.ConfirmEmailView.as_view(), name='email-confirm'),
    path('logout', app_views.SignOutView.as_view(), name='logout'),
]

src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include(('apps.accounts.urls', 'apps.accounts'), namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('charges/', include(('apps.charges.urls', 'apps.charges'), namespace='charges')),
    path('', include(('apps.core.urls', 'apps.core'), namespace='core')),
    path('', include(('apps.users.urls', 'apps.users'), namespace='users')),
    path('admin/', admin.site.urls),
    path('jet', include('jet.urls', namespace='jet')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/templates/profile/deposit.html
{% extends 'core/dashboard-base.html' %}
{% load static i18n widget_tweaks %}

{% block extra-content %}
  <section class="main-content-section section-padding">
    <div class="container">
      <div class="row">
        <div class="col-sm-12" style="padding-top: 10px;">
          {% for message in messages %}
            <div class="alert alert-primary">{{ message }}</div>
          {% endfor %}
        </div>
      </div>
      <div class="row">

        <!-- main contents wrapper -->
        <div class="col-md-8 clearfix">
          <div class="main-content-wrapper bet-wrapper">
            <div class="event-widget-wrapper">
              <!-- single bet widget ends -->
              <div class="single-bet-widget">
                <div class="media">

                  <div class="media-body">
                    <h3>{% trans 'Your Deposit' %}</h3>
                    <hr>
                    <div class="bet-details">
                      <h4>{% trans 'Deposit' %}:&nbsp;${{ user.account.get_deposit_value }}</h4>
                      <p>{{ event.notes|default:"Lorem Ipsum is simply dummy text of the printing typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since" }}.</p>
                    </div>

                    <hr/>
                    <form method="post">
                      <div class="text-right">
                        <a href="{% url 'charges:charge' %}"
                           class="btn-common btn-primary">
                          {% trans 'Refill Deposit' %}
                        </a>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- main contents wrapper ends -->
      </div>
    </div>
  </section>
{% endblock %}

src/templates/profile/profile-edit.html
{% extends 'core/dashboard-base.html' %}
{% load static i18n widget_tweaks %}

{% block extra-content %}
  <section class="main-content-section section-padding">
    <div class="container">
      <div class="row">

        <!-- main contents wrapper -->
        <div class="col-md-8 clearfix">
          <div class="main-content-wrapper bet-wrapper">
            <div class="event-widget-wrapper">
              <!-- single bet widget ends -->
              <div class="single-bet-widget">
                <div class="media">

                  <div class="media-body">
                    <h3>Edit Profile</h3>
                    <hr>
                    <div class="bet-details">

                      <div class="date">
                        <p>{% trans "Joined at" %}:&nbsp;<a
                                href="javascript:void(0);">
                          <i class="fas fa-calendar-alt"></i>
                          {{ object.date_joined|date:'d/m/Y' }}
                        </a>
                          <a href="javascript:void(0);">
                            <i class="fas fa-clock"></i>
                            {{ object.date_joined|date:'h:i A' }}
                          </a></p>
                      </div>
                      <a href="javascript:void(0);" class="team-name">
                        {{ event.teams.all|join:', ' }}
                      </a>
                      <p>{% trans "You can change your profile here" %}.</p>
                    </div>

                    <hr/>
                    <form method="post" class="form-horisontal" enctype="multipart/form-data">
                      {% if not registered_bet %}
                        {% csrf_token %}
                        {% for field in form %}
                          <div class="form-group">
                            {{ field.label_tag }}
                            {% render_field field class="form-control" %}
                          </div>
                        {% endfor %}
                        <br/>
                        <div class="text-right">
                          <input type="submit" class="btn-common btn-primary">
                        </div>
                      {% else %}
                        <div class="alert alert-success">
                          Your Bet amount: ${{ registered_bet.amount }}
                        </div>
                      {% endif %}
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- main contents wrapper ends -->

        <!-- sidebar wrapper -->
        <div class="col-md-4 clearfix">
          <aside class="sidebar-wrapper clearfix">
            <!-- Single Sidebar -->
            <div class="single-sidebar">
              <!-- title -->
              <div class="inner-section-title">
                <h2><i class="fas fa-calendar-alt"></i> Total Bets</h2>
              </div>

              <!-- sidebar widget -->
              <div class="sidebar-widget clearfix">
                <!-- single widget card -->
                {% trans 'Your total bets' %}:&nbsp;{{ user.bets.count }}
                <!-- single widget card ends -->
              </div>
            </div>

            <!-- Single Sidebar Ends -->
          </aside>
        </div>
        <!-- sidebar wrapper ends -->

      </div>
    </div>
  </section>

{% endblock %}

src/templates/profile/profile.html
{% extends 'core/dashboard-base.html' %}
{% load static i18n %}

{% block head-css %}
  {{ block.super }}
  <style>
    .profile .event-details {
      width: 100%
    }

    .profile .logout-btn {
      color: white;
      float: right;
      margin-left: 30px;
    }
  </style>
{% endblock %}

{% block extra-content %}
  <section class="main-content-section section-padding profile">
    <div class="container">
      <div class="row">

        <!-- main contents wrapper -->
        <div class="col-md-12 clearfix">
          <div class="main-content-wrapper">
            <!-- title -->
            <!-- event widgets wrapper -->
            <div class="event-widget-wrapper clearfix">
              <!-- event date -->
              <div class="event-date">
                <a href="{% url 'users:logout' %}" class="logout-btn">
                  <i class="fas fa-sign-out-alt"></i> {% trans 'Logout' %}
                </a>
                <h2>{% trans 'Your Profile' %}</h2>
              </div>
              {% with account=object.account %}
                <!-- event widgets -->
                <div class="event-widgets">
                  <!-- single event widget -->
                  <div class="single-event-widget">
                    <!-- event details -->
                    <div class="event-details">
                      <div class="container">
                        <div class="row">
                          <div class="col-md-3 col-sm-4">
                            {% if object.avatar %}
                              <img class="img-thumbnail"
                                   src="{{ object.avatar.url }}"/>
                            {% else %}
                              <img class="img-responsive"
                                   src="{% static 'assets/images/bet/bet1.png' %}"/>
                            {% endif %}
                          </div>
                          <div class="col-md-9 col-sm-8">

                            <a href="{% url 'accounts:update' %}"
                               style="color: white; float: right;"><i
                                    class="far fa-edit"></i> {% trans 'Change' %}</a>
                            <p>ID: <span>#{{ object.id }}</span></p>
                            <p>{% trans 'Full Name' %}:
                              <span>{{ object.get_full_name }}</span>
                            </p>
                            <p>{% trans 'Email' %}: <span>{{ object.email }}</span></p>
                            <p>{% trans 'Phone' %}:
                              <span>{{ object.phone|default:'-' }}</span>
                            </p>
                            <p>{% trans 'Joined At' %}:
                              <span>{{ object.date_joined }}</span>
                            </p>
                            <p>{% trans 'Last Login' %}: <span>{{ object.last_login }}</span>
                            </p>

                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              {% endwith %}
            </div>

          </div>
        </div>
        <!-- main contents wrapper ends -->
      </div>
    </div>
  </section>

{% endblock %}

src/templates/profile/register.html
{% extends 'core/base.html' %}
{% load static %}

{% block head-css %}
  <style>

    .error-list {
      color: #ff8c76;
    }

    .help-list {
      color: #ff8c76;
      position: absolute;
      right: -200px;
    }

    button {
      width: 100%;
    }

  </style>
{% endblock %}

{% block content %}
  <section class="log-in-section d-flex align-items-center">
    <div class="container">
      <div class="row justify-content-center">
        <!-- Log In section Logo -->
        <div class="col-md-4">
          <div class="log-in-logo">
            <a href="{% url 'core:index' %}">
              <img src="{% static "assets/images/logo-login.png" %}" alt="">
            </a>
          </div>
        </div>
        <!-- Log In section Logo  ends-->
      </div>

      <div class="row justify-content-center">
        <!-- Log in inouts -->
        <div class="col-md-4">
          <div class="log-in-inputs clearfix">
            <form action="" method="post">
              {% csrf_token %}
              {% include 'includes/form.html' with form=form %}
              <a href="{% url 'password_reset' %}" class="forgot-pass">Forget Password</a>
              <div class="form-group submit-group text-center">
                  <button type="submit" class="btn-common btn-red">
                    REGISTER
                  </button>
                <!-- separator -->
                <div class="separator text-center">
                  <p>or</p>
                </div>
                <p>Don't have an account yet? <a href="{% url 'login' %}">Sign In</a></p>
              </div>
            </form>

          </div>
        </div>
        <!-- Log in inouts ends -->
      </div>
    </div>
  </section>
{% endblock %}